# Generated by Django 4.2.20 on 2025-04-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='home_images/')),
                ('sqfoot', models.IntegerField()),
            ],
        ),
    ]
